stages:
    - build
variables:
    # VERSION: latest
    IMAGE_NAME: alpine/git
    
before_script: 
    # - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build:
    stage: build
    script:
        - docker load -i git_image
        - docker tag $IMAGE_NAME:latest $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:latest 
        - docker rmi $CI_REGISTRY_IMAGE:latest 
